In [1]:
import numpy as np

# Data Type and Shapes

# Scalar

In [2]:
s=np.array(50)
print(s)

50


In [3]:
print(s.shape)
print(type(s))

()
<class 'numpy.ndarray'>


In [6]:
x=s+3
print(x)
print(type(x))
print(x.shape)

53
<class 'numpy.int64'>
()


In [8]:
x=np.zeros(3)
print(x)
x.shape

[0. 0. 0.]


(3,)

In [9]:
x=np.ones(10)
print(x)
x.shape

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


(10,)

In [10]:
v=np.array([1,2,3])
print(v)
v.shape

[1 2 3]


(3,)

In [11]:
x=v[0:2]
print(x)

[1 2]


In [13]:
print(v[:1])

[1]


In [14]:
print(v[0:])

[1 2 3]


In [15]:
m=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("m = \n",m)
print(type(m))

m = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>


In [16]:
print(m[1][2])

6


In [21]:
m=[[1,2,3],[4,5,6],[7,8,9]]
print("m = \n",m)
#print("Shape of m ",m.shape)
print(type(m))

m = 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


Tensors

In [30]:
t=np.array([
    [[[1],[2]],[[3],[4]],[[5],[6]]],
    [[[7],[8]],[[9],[10]],[[11],[12]]],
    [[[13],[14]],[[15],[16]],[[17],[18]]]])

print(t[2][1][1][0])

16


In [28]:
t=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])

In [29]:
print(t.shape)

(3, 2, 1)


# Changing Shape

In [32]:
v=np.array([1,2,3,4])

In [34]:
print(v.shape)

(4,)


In [36]:
x=v.reshape(4,1)
print(x)

[[1]
 [2]
 [3]
 [4]]


In [37]:
print(x.shape)

(4, 1)


In [38]:
z=np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
ones=np.ones((2,6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [44]:
a=np.random.rand(4,4)
print(a)

[[0.4641861  0.35183694 0.42839768 0.89405681]
 [0.74276311 0.13627356 0.01771158 0.65959822]
 [0.02575526 0.20457491 0.63591667 0.12042258]
 [0.20369254 0.01331349 0.27797148 0.96881877]]
